### ISSUE TITLE
Unable to convert model

### ISSUE THREAD

**Issue by nviet** [leejet/stable-diffusion.cpp#55]
I wanted to convert [this model](https://civitai.com/models/143108/game-icon-institutev10). It's fine-tuned model based on Stable Diffusion 1.5. I got this error message:

```
python3 convert.py ~/gameIconInstituteV10_v10.safetensors --out_type f16

loading model from ~/gameIconInstituteV10_v10.safetensors
loading model from ~/gameIconInstituteV10_v10.safetensors completed
Stable diffuison 1.x
no alphas_cumprod in file, generate new one
Saving GGML compatible file to /home/user/stable-diffusion.cpp/models/gameIconInstituteV10_v10-ggml-model-f16.bin
Traceback (most recent call last):
  File "/home/user/stable-diffusion.cpp/models/convert.py", line 369, in <module>
    convert(args.model_path, args.out_type, args.out_file)
  File "/home/user/stable-diffusion.cpp/models/convert.py", line 317, in convert
    data = state_dict[name].numpy()
TypeError: Got unsupported ScalarType BFloat16
```

Is it possible to add support for this kind of model please?

**Comment by leejet** [comment]
I've updated the convert.py file. You can pull the latest code and try re-converting the model.

**Comment by nviet** [comment]
Thank you very much. It works now.
